name: 'Alfalfa'
description: 'Run an instance of Alfalfa'
inputs:
  tag:
    description: 'tag for pulling alfalfa containers'
    default: 'develop'
  worker-scale:
    description: 'number of worker to run'
    default: '1'
runs:
  using: "composite"
  steps:
    - name: Checkout Alfalfa
      uses: actions/checkout@v3
      with:
        ref: 'develop'
    - run: export VERSION_TAG=${{ inputs.tag }}
      shell: bash
    - run: docker compose up -d --scale worker=${{ inputs.worker-scale }}
      shell: bash